"""add_polls_karma

Revision ID: c5663cb7f339
Revises: c7f4c281255d
Create Date: 2026-04-18 17:06:01.567131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5663cb7f339'
down_revision: Union[str, Sequence[str], None] = 'c7f4c281255d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('karma',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nick', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('given_up', sa.Integer(), nullable=False),
    sa.Column('given_down', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_karma_nick'), 'karma', ['nick'], unique=True)
    op.create_table('polls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=128), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('answers', sa.Text(), nullable=False),
    sa.Column('starter_nick', sa.String(length=64), nullable=False),
    sa.Column('starter_hostmask', sa.String(length=256), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polls_channel'), 'polls', ['channel'], unique=False)
    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('hostmask', sa.String(length=256), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_votes_poll_id'), 'poll_votes', ['poll_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poll_votes_poll_id'), table_name='poll_votes')
    op.drop_table('poll_votes')
    op.drop_index(op.f('ix_polls_channel'), table_name='polls')
    op.drop_table('polls')
    op.drop_index(op.f('ix_karma_nick'), table_name='karma')
    op.drop_table('karma')
    # ### end Alembic commands ###
