"""initial

Revision ID: c7f4c281255d
Revises: 
Create Date: 2026-04-18 13:18:07.505602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f4c281255d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('modes', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=True)
    op.create_table('ignores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostmask', sa.String(length=256), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('set_by', sa.String(length=64), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=128), nullable=False),
    sa.Column('nick', sa.String(length=64), nullable=False),
    sa.Column('hostmask', sa.String(length=256), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_channel'), 'logs', ['channel'], unique=False)
    op.create_index(op.f('ix_logs_logged_at'), 'logs', ['logged_at'], unique=False)
    op.create_table('plugin_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=128), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_settings_plugin'), 'plugin_settings', ['plugin'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin', sa.String(length=64), nullable=False),
    sa.Column('function_name', sa.String(length=128), nullable=False),
    sa.Column('cron_expr', sa.String(length=64), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seen_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nick', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seen_entries_nick'), 'seen_entries', ['nick'], unique=False)
    op.create_index(op.f('ix_seen_entries_seen_at'), 'seen_entries', ['seen_at'], unique=False)
    op.create_table('tells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_nick', sa.String(length=64), nullable=False),
    sa.Column('to_nick', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tells_to_nick'), 'tells', ['to_nick'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nick', sa.String(length=64), nullable=False),
    sa.Column('hostmask', sa.String(length=256), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('global_flags', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_where', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_account'), 'users', ['account'], unique=False)
    op.create_index(op.f('ix_users_nick'), 'users', ['nick'], unique=False)
    op.create_table('bans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('hostmask', sa.String(length=256), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('set_by', sa.String(length=64), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bans_channel_id'), 'bans', ['channel_id'], unique=False)
    op.create_table('channel_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_settings_channel_id'), 'channel_settings', ['channel_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('author_nick', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tags', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nick', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_fire_at'), 'reminders', ['fire_at'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('user_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=128), nullable=True),
    sa.Column('flag', sa.String(length=4), nullable=False),
    sa.Column('granted_by', sa.String(length=64), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_flags_user_id'), 'user_flags', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_flags_user_id'), table_name='user_flags')
    op.drop_table('user_flags')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_fire_at'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_channel_settings_channel_id'), table_name='channel_settings')
    op.drop_table('channel_settings')
    op.drop_index(op.f('ix_bans_channel_id'), table_name='bans')
    op.drop_table('bans')
    op.drop_index(op.f('ix_users_nick'), table_name='users')
    op.drop_index(op.f('ix_users_account'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tells_to_nick'), table_name='tells')
    op.drop_table('tells')
    op.drop_index(op.f('ix_seen_entries_seen_at'), table_name='seen_entries')
    op.drop_index(op.f('ix_seen_entries_nick'), table_name='seen_entries')
    op.drop_table('seen_entries')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_plugin_settings_plugin'), table_name='plugin_settings')
    op.drop_table('plugin_settings')
    op.drop_index(op.f('ix_logs_logged_at'), table_name='logs')
    op.drop_index(op.f('ix_logs_channel'), table_name='logs')
    op.drop_table('logs')
    op.drop_table('ignores')
    op.drop_index(op.f('ix_channels_name'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
